### ISSUE TITLE
[1.0.0-alpha.0] Webpack warning 

### ISSUE THREAD

**Issue by astyfx** [pelotoncycle/resize-observer#11]
![screen shot 2018-08-21 at 5 52 43 pm](https://user-images.githubusercontent.com/4187285/44391516-0c39d300-a56b-11e8-9540-855266e2790c.png)

When using `1.0.0-alpha.0` WDS console warn me like above, it is safe to use?

- devtool option: `cheap-module-eval-source-map`

**Comment by devrelm** [comment]
Disclaimer: I'm not an expert on source maps, so I'm figuring them out as I go along.

It looks like the source map is referring to the original source file, which isn't included in the bundle. I had kept them out since I've seen errors in the past where the TypeScript compiler picks them up instead of the type declaration files, causing issues with differences in compiler settings.

That said, I think we might actually _not_ have that problem in this package. Since the distributables are kept in a separate directory from the source files, we should be ok as long as nothing in the `package.json` points at the `src/` directory.

I'll try to get a new alpha up quickly with the `src/` directory included in the package.

**Comment by astyfx** [comment]
It work like a charm! Thanks for your effort.
